config/routes.rb
Postgresspractice::Application.routes.draw do
  root 'application#index'
  get '/privacy' => 'application#privacy'

  resources :streets

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
end

app/models/street.rb
class Street < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
  end
  def privacy
  end
end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  before_action :set_street, only: [:show, :edit, :update, :destroy]

  # GET /streets
  # GET /streets.json
  def index
    @streets = Street.all
  end

  # GET /streets/1
  # GET /streets/1.json
  def show
  end

  # GET /streets/new
  def new
    @street = Street.new
  end

  # GET /streets/1/edit
  def edit
  end

  # POST /streets
  # POST /streets.json
  def create
    @street = Street.new(street_params)

    respond_to do |format|
      if @street.save
        format.html { redirect_to @street, notice: 'Street was successfully created.' }
        format.json { render action: 'show', status: :created, location: @street }
      else
        format.html { render action: 'new' }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streets/1
  # PATCH/PUT /streets/1.json
  def update
    respond_to do |format|
      if @street.update(street_params)
        format.html { redirect_to @street, notice: 'Street was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streets/1
  # DELETE /streets/1.json
  def destroy
    @street.destroy
    respond_to do |format|
      format.html { redirect_to streets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_street
      @street = Street.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def street_params
      params.require(:street).permit(:name, :treetype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/application/index.html.erb
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<a href="privacy.html">Privacy</a>

app/views/application/privacy.html.erb
<h1>Privacy Policy</h1>
<p>
  
Application Privacy Statement 

This privacy statement (“Privacy Statement”) applies to the treatment of personally identifiable information submitted by, or otherwise obtained from, you in connection with the associated application (“Application”). The Application is provided by feedme (and may be provided by feedme on behalf of a feedme licensor or partner (“Application Partner”). By using or otherwise accessing the Application, you acknowledge that you accept the practices and policies outlined in this Privacy Statement. 

WHAT PERSONAL INFORMATION DOES feedme COLLECT? 

We collect the following types of information from our users: 

Personal Information You Provide to Us:
We may receive and store any information you submit to the Application (or otherwise authorize us to obtain – such as, from (for example) your Facebook account). The types of personal information collected may include your full name, email address, gender, IP address, browser information, username, demographic information, and any other information necessary for us to provide the Application services. 

Personal Information Collected Automatically:
We receive and store certain types of usage related information whenever you interact with Application. For example, feedme may automatically receive and record information regarding your computer’s IP address, browser information, Facebook user ID, Facebook Page fan status, and URLs accessed. Such information may be shared in aggregate (non-personally identifiable) form with our partners. 

HOW DOES feedme USE THE INFORMATION IT COLLECTS? 

feedme uses the information described in this Privacy Statement (i) internally, to analyze, develop and improve its products and services, and (ii) as set forth below in the “Will feedme Share any of the personal information it Collects” section below. 

APPLICATION PARTNER TREATMENT OF PERSONAL INFORMATION. 

feedme may provide personal information to the applicable Application Partner. The Application Partner’s use of your personal information is subject to the Application Partner’s separate privacy policy – and not this Privacy Statement. The Application Partner’s privacy policy is linked to from within the Partner’s Facebook application. 

WILL feedme SHARE ANY OF THE PERSONAL INFORMATION IT RECEIVES? 

Personal information about our users is an integral part of our business. We neither rent nor sell your personal information to anyone (with the exception of sharing your information with an applicable Application Partner – see the “Application Partner Treatment” section above). We share your personal information only as described below. 

Application Partners: We will share your personal information with an applicable Application Partner (see the “Application Partner Treatment” section above). 

Agents: We employ other companies and people to perform tasks on our behalf and need to share your information with them to provide products or services to you. Unless we tell you differently, feedme’s agents do not have any right to use personal information we share with them beyond what is necessary to assist us. You hereby consent to our sharing of personal information for the above purposes. Business Transfers: In some cases, we may choose to buy or sell assets. In these types of transactions, customer information is typically one of the business assets that are transferred. Moreover, if feedme, or substantially all of its assets were acquired, or in the unlikely event that feedme goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of feedme may continue to use your personal information as set forth in this policy. 

Protection of feedme and Others: We may release personal information when we believe in good faith that release is necessary to comply with the law; enforce or apply our conditions of use and other agreements; or protect the rights, property, or safety of feedme, our employees, our users, or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction. 

With Your Consent: Except as set forth above, you will be notified when your personal information may be shared with third parties, and will be able to prevent the sharing of this information. 

CONDITIONS OF USE. 

If you decide to use or otherwise access the Application, your use/access and any possible dispute over privacy is subject to this Privacy Statement and our Terms of Use, including limitations on damages, arbitration of disputes, and application of California state law. 

THIRD PARTY APPLICATIONS/WEBSITES. 

The Application may permit you to link to other applications or websites. Such third party applications/websites are not under feedme’s control, and such links do not constitute an endorsement by feedme of those other applications/websites or the services offered through them. The privacy and security practices of such third party application/websites linked to the Application are not covered by this Privacy Statement, and feedme is not responsible for the privacy or security practices or the content of such websites. 

WHAT PERSONAL INFORMATION CAN I ACCESS? 

feedme allows you to access the following information about you for the purpose of viewing, and in certain situations, updating that information. This list may change in the event the Application changes. 

- Account and user profile information
- User e-mail address, if applicable
- Facebook profile information, if applicable
- User preferences
- Application specific data 

CAN CHILDREN USE THE APPLICATION? 

Our site and the services available through feedme are not intended for children under the age of 13. feedme does not knowingly or specifically collect information about children under the age of 13 and believes that children of any age should get their parents’ consent before giving out any personal information. We encourage you to participate in your child’s web experience. 

CHANGES TO THIS PRIVACY STATEMENT. 

feedme may amend this Privacy Statement from time to time. Use of information we collect now is subject to the Privacy Statement in effect at the time such information is used. If we make changes in the way we use personal information, we will notify you by posting an announcement on our Site or sending you an email. Users are bound by any changes to the Privacy Statement when he or she uses or otherwise accesses the Application after such changes have been first posted. 

QUESTIONS OR CONCERNS. 

If you have any questions or concerns regarding privacy on our Website, please send us a detailed message at [COMPANY-EMAIL]. We will make every effort to resolve your concerns. 

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postgresspractice</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- GOOGLE API -->
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxUZBj8AGgXyVRgcDsjZKZnbTKsGuWvaI">
  </script>

  <!-- JAVASCRIP W3 FOR DISPLAYING MAP -->
  <script>
  var x = document.getElementById("demo");

  function getLocation() {
      if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition, showError);
      } else {
          x.innerHTML = "Geolocation is not supported by this browser.";
      }
  }

  function showPosition(position) {
      var latlon = position.coords.latitude + "," + position.coords.longitude;

      var img_url = "http://maps.googleapis.com/maps/api/staticmap?center="
      +latlon+"&zoom=14&size=400x300&sensor=false";
      document.getElementById("mapholder").innerHTML = "<img src='"+img_url+"'>";
  }

  function showError(error) {
      switch(error.code) {
          case error.PERMISSION_DENIED:
              x.innerHTML = "User denied the request for Geolocation."
              break;
          case error.POSITION_UNAVAILABLE:
              x.innerHTML = "Location information is unavailable."
              break;
          case error.TIMEOUT:
              x.innerHTML = "The request to get user location timed out."
              break;
          case error.UNKNOWN_ERROR:
              x.innerHTML = "An unknown error occurred."
              break;
      }
  }
  </script>
  <!-- FACEBOOK SCRIPT -->
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '388279541346073',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
</head>
<body>

<p id="demo">Click the button to get your position.</p>

<button onclick="getLocation()">Try It</button>

<div id="mapholder"></div>


<%= yield %>

</body>
</html>

app/views/streets/_form.html.erb
<%= form_for(@street) do |f| %>
  <% if @street.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@street.errors.count, "error") %> prohibited this street from being saved:</h2>

      <ul>
      <% @street.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :treetype %><br>
    <%= f.text_field :treetype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/streets/edit.html.erb
<h1>Editing street</h1>

<%= render 'form' %>

<%= link_to 'Show', @street %> |
<%= link_to 'Back', streets_path %>

app/views/streets/index.html.erb
<h1>Listing streets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Treetype</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @streets.each do |street| %>
      <tr>
        <td><%= street.name %></td>
        <td><%= street.treetype %></td>
        <td><%= link_to 'Show', street %></td>
        <td><%= link_to 'Edit', edit_street_path(street) %></td>
        <td><%= link_to 'Destroy', street, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Street', new_street_path %>

app/views/streets/new.html.erb
<h1>New street</h1>

<%= render 'form' %>

<%= link_to 'Back', streets_path %>

app/views/streets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @street.name %>
</p>

<p>
  <strong>Treetype:</strong>
  <%= @street.treetype %>
</p>

<%= link_to 'Edit', edit_street_path(@street) %> |
<%= link_to 'Back', streets_path %>